name: Flutter

on:
  push:
    branches:
      - feature/*
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Static Analyses
    steps:
      - uses: actions/checkout@v2
      - name: Install Flutter action
        uses: subosito/flutter-action@v2.3.0
        with:
          channel: stable
      - name: Check version
        run: flutter --version
      - name: Run pub get
        run: flutter pub get
      - name: Run analysis
        run: flutter analyze
      - name: Run tests
        run: flutter test
